/* Editorial data. Add the newest entry first; each source must point to primary evidence. */
const ARTICLES = [
  {
    date:'2026-09-30', level:'HIGH', tags:['Security','MCP','Operations'],
    title:'MCP Gatewayの「安全な版」が判定できないとき',
    summary:'新たなDoS advisoryの版情報矛盾と、無人Agentで顕在化した入力・秘密管理の境界を整理する。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>Agent Routerで、存在しないbackendや未初期化sessionを狙うMCP requestがExtProcをpanicさせる新しいsecurity advisoryが公開された。</strong>severityはMEDIUM、CVSS 5.3だが、認証不要・低難度で共有processを停止でき、同時接続をまとめて切断し得る。</p><p>さらに重要なのは、advisoryが影響範囲を<code>&lt;= 1.1.0</code>、修正版も<code>1.1.0</code>と記載している点である。両者は論理的に両立しない。最新releaseを使っているという事実だけで安全と判断せず、upstreamによるversion情報の訂正または修正commitの特定まで、入口側の緩和策を維持する必要がある。</p>'},
      {heading:'重要ニュース',html:'<p><strong>GHSA-76mr-h444-pcqq — MEDIUM / CVSS 5.3</strong><br><code>getCompositeSessionEntry</code>などのsession lookupが、未登録・削除済み・設定不備のbackendに対して<code>nil</code>を返す。二つのMCP handlerは戻り値を確認せずfieldへアクセスするため、Go runtimeのnil pointer panicが発生し、ExtProc service processが終了する。advisoryのPoCは、active sessionから存在しないbackendまたはrouteを指定するJSON-RPC requestを送る手順を示している。</p><p><strong>事実：</strong>2026年9月30日朝の確認時点でCVEは未割り当てで、advisory metadataのaffected rangeとpatched versionが矛盾している。また、前回以降にAgent Routerの正式releaseは確認できない。<strong>判断：</strong>v1.1.0を修正済みとも脆弱とも断定せず、MCP endpointの到達制御、未知backend名の早期拒否、ExtProcの再起動・分離を暫定対策とする。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>Agent Router — HIGH</strong><br>上記advisoryに加え、OpenAI streaming requestへ<code>stream_options.include_usage=true</code>を注入する処理が、重複した<code>stream_options</code> keyを残さないよう修正された。JSON parserごとに最初・最後のどちらのkeyを採用するかが異なる曖昧性をなくし、最後のobjectにある追加fieldを維持しながら一つのkeyへ正規化する。これは課金・usage観測の欠落や、解析結果とupstreamへ送るbodyの不一致を防ぐ変更である。</p><p><strong>goose — MEDIUM</strong><br>MCP elicitationはstdinがterminalでない場合に明示的に拒否し、pipeに待機している次の会話入力をform回答として誤消費しないようになった。ACPの無人実行では、macOS Keychainのauthorization promptが応答者不在で無期限blockし得ることも文書化され、<code>GOOSE_DISABLE_KEYRING=1</code>と環境変数credentialの利用が案内された。</p><p>Bedrock streamingでは<code>max_tokens</code>でtool call JSONが途中切断された場合、未完了tool blockを失敗requestとしてflushし、output token limit到達をmetadataとusageへ残す。黙って不完全なtool callを進めるのではなく、Agentが再試行・task分割・上限変更を判断できる。CIでは主要GitHub Actionsのtag指定がcommit SHA固定へ置き換えられた。</p><p><strong>agentgateway — MEDIUM</strong><br>JWKSを直接URLで指定する構成では<code>BackendRef</code>がnilになり得るが、ReferenceGrant確認が無条件に参照してpanicしていた。nil checkとpolicy/backend双方の回帰testが追加された。</p><p><strong>MCP / A2A / AGENTS.md — WATCH</strong><br>MCPとAGENTS.mdに正式仕様変更はなく、A2Aはlink checker修正のみでprotocol変更ではない。新規releaseやsecurity advisoryも確認できなかった。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIF Technical Committee、Working Groups、project proposal、新規加入・卒業projectに、新しい正式決定は確認できなかった。AAIFの公式project一覧もMCP、goose、AGENTS.mdの構成を維持している。</p><p><strong>分析：</strong>今回のadvisory metadataの矛盾は、security情報そのものをmachine-readableな運用入力として扱う難しさを示す。SBOM scannerやpolicy engineがaffected rangeだけを読む場合とpatched versionだけを読む場合で判定が分かれる。標準化ではprotocol conformanceだけでなく、advisory schemaの整合性検査、訂正履歴、修正commitとのtraceabilityも供給網の要件になる。</p>'},
      {heading:'技術トレンド',html:'<p>本日の変更は、<strong>境界で曖昧さを残さない</strong>という同じ方向を向いている。MCP session lookupのnil、JSONの重複key、pipeと対話入力の混在、未完了tool call、URL指定時のnil BackendRefはいずれも、正常系では隠れる曖昧な状態である。</p><p>Agentic systemはLLM出力、protocol変換、terminal、credential store、Kubernetes resourceを連結するため、一層の曖昧さが別層の命令や秘密情報として解釈されやすい。入口で型・存在・入力channelを確定し、失敗をrequest単位の構造化errorとして返し、process全体へ拡大させない設計が重要になる。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>運用AgentやMCP GatewayのPoCでは、次を受け入れ条件へ加える。</p><ul><li>未知・削除済みbackend、期限切れsession、初期化途中sessionを送り、4xxまたはJSON-RPC errorで終わること</li><li>handler panicをprocess境界で回復し、tenantまたはrouteごとに障害半径を分離すること</li><li>advisoryのaffected rangeとpatched versionを自動比較し、矛盾時は安全側に倒して人手確認へ送ること</li><li>重複JSON keyを拒否または正規化し、policy評価bodyとupstream送信bodyを一致させること</li><li>非TTY実行でelicitationを開始せず、queued stdinを次の会話turnとして保持すること</li><li>無人ACPではKeychain promptを使わず、短命credentialまたは専用secret注入を使うこと</li><li>tool call切断を成功扱いせず、finish reasonと失敗tool requestをtraceへ残すこと</li><li>JWKS URL、BackendRef、ReferenceGrantの全組合せをcontroller testへ含めること</li></ul><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>version scannerの緑表示より一次advisoryの整合性を優先する。安全版が一意に決まらない間は、到達制御とprocess分離を解除しない。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>GHSA-76mr-h444-pcqqのversion range訂正、CVE割り当て、修正commitの公開</li><li>Agent Router次期releaseへのMCP nil checkと重複JSON key修正の収録</li><li>ExtProcのpanic recoveryとmulti-tenant障害分離</li><li>gooseの非TTY elicitation errorをACP clientがどう表示・回復するか</li><li>Keychainを使わない無人Agent向けcredential brokerの整備</li><li>Bedrock以外のproviderでも途中切断tool callを同じsemanticsで扱えるか</li><li>AAIF Security／Identity &amp; Trust WGでのadvisory整合性・credential運用指針</li></ul>'}
    ],sources:[
      ['GHSA-76mr-h444-pcqq: nil session entry checks missing in MCP handlers','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-76mr-h444-pcqq'],
      ['Agent Router: de-duplicate stream_options.include_usage','https://github.com/theagentrouter/agent-router/commit/abe39a35f4b66a866eace751f644f9842beceff5'],
      ['goose: require a terminal for elicitation input','https://github.com/aaif-goose/goose/commit/a1097dc6a2f4223f2d5f5100ea0777a1180b99c1'],
      ['goose: warn about keyring hang in unattended ACP environments','https://github.com/aaif-goose/goose/commit/7b72e902a3a58014270af91165fef5f4dfa17c2c'],
      ['goose: report Bedrock max_tokens truncation and flush tool calls','https://github.com/aaif-goose/goose/commit/9d57bad41c1e49ce7852da0f266a1821f2cb075e'],
      ['goose: pin remaining GitHub Actions to commit SHAs','https://github.com/aaif-goose/goose/commit/8171db0c9dae3f846c3aab866519e8ce19f514a4'],
      ['agentgateway: fix JWKS direct URI nil pointer','https://github.com/agentgateway/agentgateway/commit/a99934fd313f1ba2162a2e48c2c98c78da827244'],
      ['AAIF official project list','https://aaif.io/projects']
    ]
  },
  {
    date:'2026-09-29', level:'HIGH', tags:['Security','MCP','Operations'],
    title:'MCP sessionを暗号化するだけでは、利用者境界は守れない',
    summary:'subject bindingとランダムseed、未信頼repository対策から、Agent実行基盤のidentity境界を考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>MCP session tokenを暗号化していても、全環境が同じ公開seedを使えば利用者境界は成立しない。</strong>Agent Routerではsession再開時にrequest subjectを必ず照合する修正に加え、Helm chartが使っていた<code>default-insecure-seed</code>を廃止し、installごとに64文字のランダムseedを生成する修正がmainへ入った。</p><p>公開seedを知る者は、観測した<code>Mcp-Session-Id</code>を復号し、subjectを差し替えて再暗号化できるため、subject checkだけを追加しても迂回できる。identityをtokenへ結び付ける処理と、tokenを保護する鍵管理は一体で設計する必要がある。</p>'},
      {heading:'重要ニュース',html:'<p><strong>Agent Router — MCP sessionのsubject binding</strong><br>session再開時に、保存されたsessionのsubjectと現在のrequest subjectを照合するよう変更された。session IDを知っているだけで別利用者がsessionを再開する経路を閉じるための修正である。</p><p><strong>Helm chart — session encryption seedの安全化</strong><br>seed未指定時はinstall時にランダム値を生成し、専用Kubernetes Secretへ保存する。upgradeでは<code>lookup</code>により同じSecretを再利用し、controllerへはDeployment引数ではなく環境変数で渡す。GitOpsの<code>helm template</code>ではlookupが使えないため、利用者管理Secretを指定する<code>existingSecret</code>も追加された。</p><p>旧chartの既定seedから更新すると既存MCP sessionは一度失効する。可用性のために公開seedをfallbackへ残すことは可能だが、security上は短い移行期間に限定すべきである。これらはmain上の変更であり、次期正式releaseへの収録を確認する必要がある。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>goose — HIGH</strong><br>review機能がrepository設定の<code>diff.external</code>を実行しないよう、すべての<code>git diff</code>へ<code>--no-ext-diff</code>を追加した。未信頼repositoryをreviewしただけで外部commandが起動する経路を閉じるsecurity修正で、commitはGHSA-6mg9-3cvh-9939への対応と明記している。advisory本文は現時点で公開一覧から確認できないため、影響version・severityは未確認として扱う。</p><p>model metadataはmodels.devからlive取得し、失敗時はbundled catalogへfallbackする方式へ進んだ。15秒timeout、32 MiB上限、ETag、atomic cache、空catalog・重複ID検証を備える。GDK Provider APIにもmodel discoveryが追加された。</p><p><strong>MCP — MEDIUM</strong><br>Ruby SDKがTier 2からTier 1へ昇格した。2025-11-25と2026-07-28の要件セットに対しserver 67/67、client 50/50のconformance、issue triage、policy整備などが根拠として示されている。</p><p><strong>agentgateway — LOW</strong><br>CELによるbody変換結果がnullの場合、upstream bodyを消去せず元のbodyを維持する修正が入った。backend CEL contextからservice workload endpointを除外する整理も行われた。</p><p><strong>A2A / AGENTS.md — WATCH</strong><br>前回観測後、正式仕様・重大release・security advisoryに相当する新しい差分は確認できなかった。</p>'},
      {heading:'ガバナンスと標準化',html:'<p><strong>MCPのSEP提出プロセスが変更された。</strong>SEP pull requestを開く前に、関連WGまたはIGのDiscord、meeting notes、GitHub Discussionで提案を議論し、そのlinkをPRへ記載することが必須になった。事前議論のないSEPは受理されない。またrepositoryがSEP PRを受け付けるのはcollaboratorのみであることも明記された。</p><p>これは仕様案をPRへ直接持ち込む方式から、WG・IGで問題設定と支持を確認してからformal processへ進む方式への変更である。レビュー負荷と重複提案を減らす一方、外部提案者は適切なgroupとcollaboratorへ到達する導線が必要になる。</p><p>AAIF全体のTechnical Committee、新規project proposal、加入・卒業projectについて、これ以外の正式変更は確認できなかった。</p>'},
      {heading:'技術トレンド',html:'<p>本日の差分には二つのtrust boundaryがある。一つはnetwork sessionで、token暗号化、鍵のentropy、subject binding、rotationが揃って初めてidentity境界になる。もう一つはlocal repositoryで、Agentが読むcodeだけでなく<code>.git/config</code>やhook、external diffもuntrusted inputとして扱う必要がある。</p><p>またmodel catalogのlive更新により、binaryを更新せず新model・価格・能力へ追随できる一方、remote metadataがAgentのmodel選択やcost計算へ影響する。size limit、schema validation、cache、bundled fallbackを備えた段階的な外部データ取り込みが標準パターンになりつつある。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>ホスティング運用のMCP Gateway・運用Agent PoCでは、次を確認する。</p><ul><li>異なる利用者のtokenで同一MCP sessionを再開できない</li><li>session seedを環境ごとに生成し、Secret managerまたはKubernetes Secretで管理する</li><li>seed rotation時のsession失効、rollback、監査手順をrunbook化する</li><li>GitOps renderごとにseedが変わらないよう既存Secretを明示する</li><li>未信頼repositoryでgit hook、fsmonitor、diff.external、textconvが実行されない</li><li>remote model catalogが取得不能・巨大・破損・空でもbundled dataで安全に継続する</li><li>model metadataの取得元、ETag、更新時刻を監査ログへ残す</li></ul><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>暗号化済みtokenという表示だけで安全と判断しない。誰が鍵を知り、どのidentityへ再利用でき、rotation時に何が止まるかまで確認する。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>Agent Routerのsession修正を含む正式releaseとsecurity advisory</li><li>公開既定seedを拒否して起動失敗にするhardening</li><li>goose GHSA-6mg9-3cvh-9939の公開advisoryと影響version</li><li>models.dev live catalogの署名・provenance・rollback方法</li><li>MCP SEP事前議論ルールによるproposal throughputの変化</li><li>Ruby SDK Tier 1のrelease追随速度とproduction事例</li></ul>'}
    ],sources:[
      ['Agent Router: bind resumed MCP sessions to request subject','https://github.com/theagentrouter/agent-router/commit/0d1e73037076d72251342d0ea578a36ffb7002c7'],
      ['Agent Router: generate random session encryption seed in Helm','https://github.com/theagentrouter/agent-router/commit/994579660ae2a9f2feef3cb77766e155746858b4'],
      ['goose: remediate external git diff security issue','https://github.com/aaif-goose/goose/commit/3fbea00fd44f6496ee4afe2b8b2897c3c95d63e9'],
      ['goose: live models.dev metadata with bundled fallback','https://github.com/aaif-goose/goose/commit/4dea9b483efbd2541d43500b8ed3c044c65e6d2f'],
      ['goose GDK: add model discovery to Provider API','https://github.com/aaif-goose/goose/commit/c30c6d160e900e126d587a06875d764b99d0e377'],
      ['MCP: require WG or IG discussion before SEP submission','https://github.com/modelcontextprotocol/modelcontextprotocol/commit/b3e2cc7a137f9c7d4335399300ad576cc4a66b68'],
      ['MCP: promote Ruby SDK to Tier 1','https://github.com/modelcontextprotocol/modelcontextprotocol/commit/70480219e37e33ac0f7ec286779e24c4b58e1950'],
      ['agentgateway: preserve upstream body on null CEL result','https://github.com/agentgateway/agentgateway/commit/c9573ed1a2664b2415d6b60994e7fe0b966bdd76']
    ]
  },
  {
    date:'2026-09-28', level:'HIGH', tags:['Security','MCP','Operations'],
    title:'MCP GatewayでSecretをSecretのまま扱う',
    summary:'HTTPRouteへのAPI key露出とToolCall起因の共有プロセス停止から、Agent Gatewayの秘密管理と障害分離を考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>Agent Gatewayの安全性は、Secretを受け取れるかではなく、受け取ったSecretを非機密resourceやログへ展開しないかで決まる。</strong>前回観測後、Agent Routerからさらに2件のsecurity advisoryが公開された。MCP backend用API keyを生成HTTPRouteへ平文で埋め込む問題と、tool call IDの欠損により共有extproc processをpanicさせられる問題である。</p><p>いずれも旧称Envoy AI Gatewayの0.4.0〜0.7.0が対象で、advisory上の修正版は1.0.0。最新正式release v1.1.0は修正済みの範囲だが、0.x imageが残る検証環境、manifest、private registryの棚卸しは引き続き必要である。</p>'},
      {heading:'重要ニュース',html:'<p><strong>GHSA-3x83-9r4x-q3px — MEDIUM / CVSS 6.5</strong><br><code>MCPRoute</code>がbackend API keyをSecret参照で受け取っても、controllerが値を解決し、生成する<code>HTTPRoute</code>のheader modifierまたはquery parameterへ平文で埋め込んでいた。HTTPRouteのread権限はSecretより広く付与されやすく、etcd暗号化の対象にも通常含まれない。query parameter方式ではEnvoyや中間proxyのaccess logにも残り得る。つまりSecret RBACを迂回してcredentialを参照できる経路が生まれる。</p><p><strong>GHSA-5gx6-2mh3-32v4 — HIGH / CVSS 7.5</strong><br>OpenAI形式のtool callにIDがないrequestをAnthropic、Bedrock-Anthropic、Gemini backendへ変換すると、pointerの未検証dereferenceでpanicする。gRPC recovery interceptorやprocess-level recoverがないため、攻撃対象requestだけでなくpod上の全tenantが利用するextproc processが停止する。境界入力の一項目欠損が共有data plane障害へ拡大する問題である。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>Agent Router — HIGH</strong><br>上記2件のadvisoryを確認した。前日に公開された4件と合わせ、0.x系について入力上限、SSE解析、credential配置、ログredaction、Kubernetes namespace境界、panic recoveryを一括で見直す必要がある。今回の観測期間に新しい正式releaseはなく、最新版はv1.1.0のままである。</p><p><strong>agentgateway — MEDIUM</strong><br>管理UIでvirtual API keyを作成する際、raw keyではなくSHA-256 hashを保存する方式が標準になった。raw keyは作成直後に一度だけ表示され、以後はhintのみを表示する。HTTPSまたはlocalhostでWeb Crypto APIが利用できない場合はraw保存へfallbackするため、UIを安全なoriginで提供することも要件になる。</p><p><strong>MCP / A2A / goose / AGENTS.md — WATCH</strong><br>前回観測後、正式仕様、重大release、security advisoryとして報告すべき追加差分は確認できなかった。agentgatewayではIstio依存関係の更新も行われたが、利用者向けの機能変更としては扱わない。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIF Technical Committee、Working Groups、project proposal、新規加入・卒業projectについて、新しい正式決定は確認できなかった。今回の問題はMCP protocolではなく、Gateway controllerがcredentialを別resourceへ変換する実装と、protocol translationの入力検証に属する。</p><p><strong>分析：</strong>MCPやA2Aの標準適合試験に加えて、SecretがどのKubernetes object、xDS config、log、metricへ複製されるかを追跡するcredential lineageが必要である。仕様上正しい通信でも、control plane内で秘密情報が広いread権限へ変換されれば安全とは言えない。</p>'},
      {heading:'技術トレンド',html:'<p>二つの更新は、credentialの扱いに対照的な方向を示す。Agent Routerの旧実装はSecretを取得後にHTTPRouteへ平文展開した一方、agentgatewayは照合に必要なhashだけを保存し、raw keyを再表示できない設計へ進んだ。</p><p>理想は、Gateway controllerがcredential本体をresource specへ書かず、Secret参照、専用credential provider、短命token、workload identityをdata planeへ安全に解決させる構成である。またprotocol translatorは外部入力を完全とは仮定せず、required field validationとpanic recoveryを二重に持つ必要がある。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>ホスティング運用でMCP GatewayをPoCする場合、次の検査を追加する。</p><ul><li><code>kubectl get httproute -A -o yaml</code>等の生成resourceにtokenやAPI keyが含まれない</li><li>etcd backup、GitOps diff、Kubernetes audit event、proxy access logへcredentialが複製されない</li><li>API keyはhash保存または外部Secret store参照とし、作成時以外はraw値を表示しない</li><li>tool callのID、name、argumentsを欠損・null・異常型にしてもrequest単位の4xxで終了する</li><li>translator panicをprocess境界でrecoverし、一つのtenant入力が他tenantへ波及しない</li><li>旧0.x imageをregistry、Helm values、検証cluster、開発端末まで含めて検索する</li></ul><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>SecretをSecret objectへ置くだけでは不十分。controllerが生成する全resourceとlogを含め、平文credentialの到達先を実測する。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>追加2件へのCVE割り当てと詳細なupgrade guidance</li><li>Agent Routerのpanic recovery、required field validationの回帰試験</li><li>MCP backend credentialをHTTPRouteへ埋め込まない現行実装の設計</li><li>agentgatewayのhashed key管理がAPI・CLIでも一貫するか</li><li>短命credential、SPIFFE、workload identityによるstatic key削減</li><li>AAIFでのcredential lineageとmulti-tenant isolationの共通指針</li></ul>'}
    ],sources:[
      ['GHSA-3x83-9r4x-q3px: MCP backend API key in HTTPRoute spec','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-3x83-9r4x-q3px'],
      ['GHSA-5gx6-2mh3-32v4: ToolCall ID nil dereference DoS','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-5gx6-2mh3-32v4'],
      ['agentgateway: support and default to hashed keys','https://github.com/agentgateway/agentgateway/commit/7e47ceb576aa9d3300cb0d2c7c35848fb0af048f'],
      ['agentgateway: bump Istio dependency','https://github.com/agentgateway/agentgateway/commit/e10197ad4884a2971807ccc97763d46f813ea907']
    ]
  },
  {
    date:'2026-09-27', level:'HIGH', tags:['Security','MCP','Operations'],
    title:'Agent Routerの4件の脆弱性が示す、MCP Gatewayの防御境界',
    summary:'MCPの巨大POST、Secret書き込み、SSE解析、APIキーログ露出から、Gateway運用で必要な多層防御を整理する。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>Agent Routerから4件のsecurity advisoryが2026年9月27日（日本時間）に公開された。</strong>対象は旧称Envoy AI Gatewayの0.3.0〜0.7.0で、修正版は1.0.0とされている。現在の最新正式releaseはv1.1.0のため、1.xへ更新済みなら各advisory上は修正済みだが、旧版を残す検証環境や固定imageは直ちに棚卸しが必要である。</p><p>内容はMCP POST bodyによるmemory exhaustion、Kubernetesのlabelを悪用したAPI-key Secretの別namespaceへの書き込み、Anthropic SSE indexによる巨大allocation、<code>aigw run</code>のログへの平文API key出力である。単一の実装不備ではなく、入力・identity・stream・secretというGatewayの四つの境界にまたがる。</p>'},
      {heading:'重要ニュース',html:'<p><strong>GHSA-43xg-mvg9-qwpq — HIGH / CVSS 7.5</strong><br>MCP proxyがPOST bodyを上限なしで<code>io.ReadAll</code>していた。ネットワークから到達できる攻撃者は巨大bodyでextproc sidecarをOOM killし、同じpodを共有するAI Gateway全体を停止させられる。認証前にbodyを読む経路であり、securityPolicy未設定のMCPRouteでは未認証攻撃が可能と説明されている。</p><p><strong>中程度の3件</strong><br>ラベルを偽装したPod・Deployment・DaemonSetのnamespaceがfilter-config Secretの書き込み先として使われ、API keyを含むSecretが攻撃者側namespaceへ生成され得る問題、悪意あるAnthropic互換upstreamがSSEの<code>index</code>を巨大値・負値にしてOOMまたはpanicを起こす問題、<code>aigw run</code>が平文API keyを含む全configをInfo logへ出す問題が公開された。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>Agent Router — HIGH</strong><br>正式advisoryとは別にmainではMCP認可が強化された。CEL式の評価エラーをrule不一致として後続Allowへ通すのではなく、対象source・targetが一致する場合はdenyするfail-closedへ変更された。また、CELで<code>request.auth.jwt</code>を参照するauthorization・backend selectionにはOAuthを必須とし、未検証JWTのclaimで認可や接続先を操作できないようにした。BackendSecurityPolicyが別namespaceのSecretを参照する場合にはReferenceGrantも必須化され、release noteでbreaking changeとして告知すべき変更と明記されている。</p><p>observabilityではGenAI metricsへ<code>gen_ai.backend</code>が追加された。同じOpenAI互換schemaを持つ複数backendでも、error rate・latency・token usageを<code>namespace/name</code>単位で区別できる。</p><p><strong>agentgateway — LOW</strong><br>Substrateのactor identity変更後に壊れていたegress認可とcredential injectionを、新しいSPIFFE URIへ追随させる修正を確認した。model catalogの自動更新も行われた。</p><p><strong>MCP / A2A / goose / AGENTS.md — WATCH</strong><br>前回記事以降、正式仕様・重大release・新規security advisoryとして扱う追加変更は確認できなかった。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIF Technical Committee、Working Groups、project proposal、新規加入・卒業projectについて、新しい正式決定は確認できなかった。今回のadvisoryはAgent Router実装のsecurity情報であり、MCP仕様そのものの脆弱性とは区別する。</p><p><strong>分析：</strong>一方で、MCP Gatewayを共通基盤として運用する際に必要な実装要件は明確になった。protocol準拠だけでは不十分で、HTTP body上限、stream fieldの範囲検証、JWT検証済み状態の伝播、Kubernetesのnamespace境界、secret redactionまでconformanceの外側で確認する必要がある。</p>'},
      {heading:'技術トレンド',html:'<p>Agent Gatewayでは「認証を付けたから安全」では足りない。今回の事例を防御層へ対応させると、入口のrequest size・timeout、認可式のfail-closed、upstream responseをuntrustedとするparser制限、Kubernetes ReferenceGrantとnamespace-scoped RBAC、ログのsecret redactionが必要になる。</p><p>また、<code>gen_ai.provider.name</code>だけではOpenAI互換backendを識別できないため、実backendを示すmetric attributeが追加された。マルチbackend構成では、セキュリティイベントとSLOを同じbackend identityで追跡できることが重要になる。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>Prometheus MCPやAlertmanager MCPをGateway経由で公開するPoCでは、次を受け入れ条件へ追加する。</p><ul><li>MCP POST body上限とrequest timeoutをGateway・sidecarの両方へ設定する</li><li>欠損fieldや型不一致でCEL評価を失敗させ、必ずdenyになることを試験する</li><li>JWT claimを使うrouteでは署名・issuer・audience検証なしに設定を受理しない</li><li>巨大・負のSSE index、途中切断、CRLF framingを含むhostile upstream試験を行う</li><li>controllerのListとSecret書き込みをnamespaceで制限し、cross-namespace参照にはReferenceGrantを要求する</li><li>CI artifact、support bundle、Info logにAPI keyが残らないことを自動検査する</li></ul><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>最初に確認すべきは、稼働・検証・手元環境を含め0.x imageが残っていないかである。1.x移行後も、同種の回帰を検出するnegative testを継続する。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>4件のadvisoryにCVEが割り当てられるか</li><li>main上のCEL・JWT・ReferenceGrant修正を含む次期正式release</li><li>MCP request body上限値とupgrade guidanceの公式文書化</li><li><code>gen_ai.backend</code>のOpenTelemetry semantic conventionsへの扱い</li><li>agentgateway v1.6.0の正式releaseとidentity・catalog互換性</li><li>AAIF SecurityまたはIdentity & Trust WGでの共通ガイドライン化</li></ul>'}
    ],sources:[
      ['GHSA-43xg-mvg9-qwpq: Unbounded MCP POST Body Memory Exhaustion','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-43xg-mvg9-qwpq'],
      ['GHSA-4mj2-4v82-3m96: Cross-namespace API-key Secret write','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-4mj2-4v82-3m96'],
      ['GHSA-vgp6-h389-r473: Unbounded SSE index allocation','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-vgp6-h389-r473'],
      ['GHSA-qv6v-2357-v3gm: API keys exposed in logs','https://github.com/theagentrouter/agent-router/security/advisories/GHSA-qv6v-2357-v3gm'],
      ['Agent Router: CEL evaluation errors fail closed','https://github.com/theagentrouter/agent-router/commit/ec0f9817114f4927331a1e3b2e4af2c2c1627495'],
      ['Agent Router: require OAuth for JWT-dependent CEL','https://github.com/theagentrouter/agent-router/commit/32add09382ed7e6cbdd0c20b278b1a1c128a578a'],
      ['Agent Router: require ReferenceGrant for cross-namespace Secrets','https://github.com/theagentrouter/agent-router/commit/780fcf46b2a39a42b2c4cf67c987b318a86b77b6'],
      ['Agent Router: add gen_ai.backend metric attribute','https://github.com/theagentrouter/agent-router/commit/00883b5859dbcca374d7561a3bff117fca18563f'],
      ['agentgateway: fix Substrate egress identity handling','https://github.com/agentgateway/agentgateway/commit/9e78d1da3286dbca730b33e243cd8e153c773751']
    ]
  },
  {
    date:'2026-09-26', level:'HIGH', tags:['Operations','Security','MCP'],
    title:'Agent Routerで露呈した、AI Gatewayの障害半径',
    summary:'異種リスナー混在時の制御面障害とストリーム処理のメモリ改善から、Agent Gatewayの本番運用設計を考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>AI Gatewayの成熟度は、対応モデル数よりも「一つの異常を制御面全体へ波及させないか」で測る段階に入った。</strong>Agent Routerでは、HTTP Connection Managerを持たないTCP・UDP用filter chainを正常な構成として読み飛ばさず、変換エラーとして扱っていた問題が修正された。</p><p>HTTP推論GatewayとTCP・UDP Gatewayを同じcontrol planeで扱う構成では、この問題によりxDS変換全体が失敗し、すべてのGatewayが<code>Programmed=False</code>となり、dataplaneが不正な設定を拒否して再起動を繰り返す可能性があった。修正後はHTTP filterを挿入できないchainだけをskipし、HTTP chainへの処理を継続する。</p>'},
      {heading:'重要ニュース',html:'<p><strong>Agent Router — 制御面の障害分離</strong><br>修正は、HCMが存在しないことを示すsentinelだけをskip条件とし、将来発生し得る本物のエラーは握りつぶさない。TCP proxy chainとHCM chainが混在するlistenerを使った回帰テストも追加された。単なるnil-checkではなく、正常な異種構成と異常を区別する変更である。</p><p><strong>Anthropic streaming — メモリ使用量の改善</strong><br>stream chunkをfoldする処理が、増え続けるtext・thinking・tool argumentsを毎回連結し、長い応答で二次的にallocationを増やしていた。<code>strings.Builder</code>を使う修正では、1 MiB・8,192 deltaの計測で累積allocationが約4.33 GB/opから約8.05 MB/opへ減少したと報告されている。これはmaintainerの限定的なbenchmarkであり一般性能を保証しないが、長時間streamをtraceするgatewayには重要な改善である。</p><p>同時に、Anthropicのusage情報を参照共有したまま更新し、元chunkや先に返したresponseのtoken数まで変えてしまう問題も修正された。observabilityと課金・quota判断の基礎データを守るcorrectness修正として重要である。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>Agent Router — HIGH</strong><br>異種listenerによるcontrol plane障害、Anthropic streamの二次allocation、usageのmutationを修正した。GCP/Gemini経路では、vLLM v0.12.0の新しい<code>structured_outputs</code>形式への対応も追加され、OpenRouterを実providerとして試験するdata-plane coverageも入った。最新正式releaseはv1.1.0のため、これらのmain上の修正がどのreleaseへ含まれるかは今後の確認が必要である。</p><p><strong>goose — MEDIUM</strong><br>modelごとのvision対応可否をprovider別の分岐ではなくcanonical catalogから解決する修正が入った。複数providerを切り替えるAgentでは、能力判定の一元化が誤った画像入力やprovider依存挙動を減らす。</p><p><strong>agentgateway — MEDIUM</strong><br>古いbinaryがmain上の新しいmodel catalogを取得した際、未知fieldでrefreshが壊れないようdeserializationを寛容にする修正が入った。v1.6.0で先に互換処理を配布し、その後にcatalog fieldを追加する方針がcommitに明記されている。</p><p><strong>A2A — LOW</strong><br>x402支払いendpointをAgentが発見・検証するdirectoryがpartners一覧へ追加された。ただしdocumentation上のecosystem追加であり、A2A protocol自体の変更ではない。</p><p><strong>MCP / AGENTS.md — WATCH</strong><br>前回観測後に、記事の中心に据える新しい正式仕様、重大release、Technical Charter変更は確認できなかった。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIF Technical Committee、Working Groups、project proposal、新規加入・卒業projectについて、この観測期間に新しい正式決定は確認できなかった。Agent Routerは2026年9月9日にAAIFへ加入済みであり、本日の変更はその後の通常開発である。</p><p><strong>分析：</strong>foundationの価値は名称やproject数だけでなく、異なるprovider・protocol・runtimeを跨ぐ不具合が公開され、回帰テストとrelease lifecycleへ取り込まれることにある。個別commitと正式な標準変更は分けて記録する必要がある。</p>'},
      {heading:'技術トレンド',html:'<p>今回の差分は、Agentic infrastructureで重要になる三つの境界を示す。</p><ul><li><strong>障害境界</strong>：一つの非HTTP chainがcontrol plane全体を止めない</li><li><strong>資源境界</strong>：長いstreamやtool argumentsがmemoryを二次的に消費しない</li><li><strong>schema境界</strong>：新しいcatalog fieldを古いbinaryが安全に無視できる</li></ul><p>ModelやToolを増やすほど、gatewayは単なる中継器ではなく、互換性と障害半径を管理するcontrol planeになる。MCP・A2A・LLM APIを一つのgatewayへ集約するなら、protocol別の機能試験に加え、共存時のfailure isolationを確認しなければならない。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>ホスティング運用のPoCで、Incident Agent、Prometheus MCP、Alertmanager MCP、将来のA2A Agentを同一gateway配下へ置く場合、次を受け入れ条件へ加える。</p><ul><li>HTTP、TCP、UDP listenerを混在させても、無関係なrouteの設定反映が止まらない</li><li><code>Programmed</code> condition、xDS rejection、dataplane再起動回数を監視する</li><li>1 MiB級のstream、数千delta、長いthinking・tool argumentsでheapとGCを測る</li><li>token usageが途中集計やtrace処理で書き換わらないことを検証する</li><li>catalog更新をcanary環境で先行取得し、旧binaryのforward compatibilityを確認する</li></ul><p><strong>分析：</strong>Agentの回答品質試験だけでは、今回の障害は見つからない。control plane、data plane、protocol adapter、Agent業務E2Eを分離して試験し、どの層の失敗かを判定できるtraceを残す必要がある。</p><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>「一つの壊れた設定が、無関係なAgentやToolの通信を止めない」をgateway PoCの最重要SLOとして扱う。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>Agent Routerの各修正を含む次期正式releaseとupgrade guidance</li><li>Anthropic stream改善の実環境memory・latency検証</li><li>Agent RouterでのMCP・LLM・TCP/UDP混在構成の回帰試験</li><li>agentgateway v1.6.0の正式releaseとcatalog互換性</li><li>gooseのcanonical model catalogを使った能力判定</li><li>A2Aとx402を組み合わせる場合のidentity、支払い承認、監査</li></ul>'}
    ],sources:[
      ['Agent Router: skip non-HCM filter chains','https://github.com/theagentrouter/agent-router/commit/2b59b939bc12d1b21d51fbdb80d8d3d529da54cb'],
      ['Agent Router: avoid quadratic stream folding allocation','https://github.com/theagentrouter/agent-router/commit/0a62cda2de54563ffab18e8a3c15a83088078096'],
      ['Agent Router: avoid mutating stream chunk usage','https://github.com/theagentrouter/agent-router/commit/e04c86ae6a8d87a51febff8b69198700c74563cf'],
      ['goose: canonical catalog for vision support','https://github.com/aaif-goose/goose/commit/04ed836c8cde23e540cc77d256992e00be99298b'],
      ['agentgateway: tolerate unknown catalog fields','https://github.com/agentgateway/agentgateway/commit/dc376ec75483292f45a1fa4ec58405319845561e'],
      ['A2A: add x402-list partner','https://github.com/a2aproject/A2A/commit/72b3761bd84c59291da694dcd97cdfc2c010df39']
    ]
  },
  {
    date:'2026-09-25', level:'HIGH', tags:['A2A','MCP','Operations'],
    title:'A2AとMCPで始まる、プロトコルのバージョン運用',
    summary:'A2A JavaScript SDK v1.2.1の修正とMCP Skills拡張から、Agentic AI基盤に必要になる互換性管理と能力配布を考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p><strong>A2Aでも、プロトコルのバージョンを本番環境で正しく扱うことが主要課題になってきた。</strong>JavaScript SDK v1.2.1は新しい仕様を追加するリリースではなく、<code>A2A-Version</code>を使った振り分けとレスポンス検証を修正するリリースだった。</p><p>MCPで進むprotocol negotiationと並べると、Agentic AI基盤は仕様を決める段階から、複数の仕様・SDKバージョンを安全に共存させる段階へ進み始めている。</p>'},
      {heading:'重要ニュース',html:'<p>A2A JavaScript SDK <strong>v1.2.1（2026年9月24日）</strong>では、JSON-RPCエラーをHTTP 200で返す修正、<code>A2A-Version</code>に基づくJSON-RPC dispatch、JSON-RPCレスポンスのバージョン検証が入った。</p><p>ほかにも、task status・artifact eventのmetadata伝播、RESTでpush notification設定を作る際のtask ID、Agentの<code>defaultInputModes</code>に対するmedia type検証が修正されている。個々には小さな修正だが、異なる実装間で通信するプロトコルでは、この種のcorrectnessが相互運用性を左右する。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>A2A — HIGH</strong><br>公式プロジェクトには複数言語のSDK、CLI、Inspector、TCK、Integration Testing Kitが揃いつつある。SDKの修正とテスト基盤を組み合わせ、仕様から実装互換性まで確認する構造が見えてきた。</p><p><strong>MCP — MEDIUM</strong><br><code>ext-skills</code>は、MCP primitivesを使ってSkillsを発見・配布する公式拡張を管理している。SEP-2640を基礎とし、2026-07-28のbase protocolに対して定義されている。MCPがtools・resources・promptsに加え、Agentが利用する能力の配布にも広がる可能性がある。</p><p><strong>Agent Router / agentgateway / goose / AGENTS.md — WATCH</strong><br>この日の確認範囲では、記事の中心に据える大型リリースは確認できなかった。既存のgateway、identity、policy、observabilityの実装動向を継続して追う。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIFのHosted ProjectsとWorking Groupsについて、この日はfoundation全体の構造を変える正式発表を確認していない。個別リポジトリの更新だけを新しい標準やガバナンス変更とは扱わない。</p><p>Skills over MCPは公式拡張として文書化が進む一方、配布されるSkillの信頼性、必要権限、依存関係、ホスト側の検証は運用上の論点として残る。</p>'},
      {heading:'技術トレンド',html:'<p>MCPとA2Aは別の役割を持つが、運用面では同じ課題へ到達している。</p><ul><li>MCP：AgentとToolの間でprotocol versionを扱う</li><li>A2A：Agent間通信で<code>A2A-Version</code>を扱う</li><li>各SDK：仕様を実装し、旧版との互換性を管理する</li><li>TCK / ITK / Conformance：実装間の差異を検出する</li></ul><p>ここから、<strong>Protocol Version Lifecycle Management</strong>が独立した運用領域になる。Kubernetes APIやTLSと同様に、対応版の一覧、段階的な更新、廃止時期、互換性試験が必要になる。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>Incident AgentがA2AでDiagnostic Agentを呼び、Diagnostic AgentがMCP経由でPrometheusやAlertmanagerへ接続する構成では、<strong>A2A version × A2A SDK version × MCP version × MCP SDK version</strong>の組み合わせが生まれる。</p><p>PoCの試験は次の3層に分けると、失敗の場所を特定しやすい。</p><ul><li><strong>A2A TCK / ITK</strong>：Agent間通信とSDK相互運用性</li><li><strong>MCP Conformance</strong>：Tool接続とprotocol correctness</li><li><strong>業務E2Eテスト</strong>：障害調査の正しさ、権限、timeout、監査ログ</li></ul><p><code>ext-skills</code>が成熟すると、運用AgentがSkill registryから必要な手順を取得し、MCP Toolを通じてインフラを調査する構造も考えられる。ただし、外部から得たSkillを実行可能な指示として扱うため、署名、許可された権限、配布元の信頼性を同時に設計する必要がある。</p><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>PoCの段階から利用バージョンを記録し、更新時には同じ障害シナリオを再実行する。互換性試験をAgentの回答評価と分けて管理する。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>A2A v1.xの次期変更と各SDKへの反映</li><li>A2A TCK / ITKによる実装間テスト</li><li>MCP 2026-07-28の各言語SDKとconformance</li><li>MCP Skills拡張のtrust modelと実装事例</li><li>Agent Routerとagentgatewayの責務境界</li><li>Identity & Trust、Observability & Traceabilityの各WG</li></ul>'}
    ],sources:[
      ['A2A JavaScript SDK v1.2.1 release','https://github.com/a2aproject/a2a-js/releases/tag/v1.2.1'],
      ['A2A Integration Testing Kit','https://github.com/a2aproject/a2a-itk'],
      ['MCP Skills extension','https://github.com/modelcontextprotocol/ext-skills']
    ]
  },
  {
    date:'2026-09-24', level:'MEDIUM', tags:['A2A','Operations'],
    title:'A2A CLIが作る、既存Agentから標準プロトコルへの移行路',
    summary:'既存の運用Agentを全面改修せず、CLIを橋渡しとしてA2A Agentへ仕事を委譲する段階的な導入方法を考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p>A2A CLIの役割は、人間がAgentを試すためのコマンドだけではない。<strong>A2A layerを持たないmodel、Agent、coding harnessからA2A Agentへ仕事を渡すbridge</strong>として設計されている。</p><p>既存のAgent runtimeをすぐにA2A SDKへ移行しなくても、shellやtool callを使えるAgentならA2A ecosystemへ接続できる。導入時の改修範囲を小さくできる点が実務上の価値になる。</p>'},
      {heading:'重要ニュース',html:'<p>公式A2A CLIはAgent Cardの取得、message送信、streaming、protocol-nativeなJSON出力、予測可能なexit codeを提供する。A2Aに対応していないAgentからも、CLIをtoolとして呼び出すことでremote A2A Agentへtaskを渡せる。</p><p>この日のA2A関連リポジトリでは複数SDKとCLIの更新が続いた。一方、正式仕様の最新版とリポジトリの更新日時は区別する必要がある。SDKの更新だけを新しいprotocol releaseとは扱わない。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>A2A — MEDIUM</strong><br>Go SDKはclient/serverとgRPC、REST、JSON-RPCの各transportを提供する。CLIを含む周辺ツールの整備により、仕様を読むだけでなく、Agentを発見・接続・検証する導線が形成されている。</p><p><strong>MCP — WATCH</strong><br>A2Aで呼ばれたremote AgentがMCP Toolを利用する構成が自然になる。A2AとMCPのどちらか一方だけを評価しても、実際の運用経路全体は確認できない。</p><p><strong>Agent Router / agentgateway — WATCH</strong><br>Agent間・Tool間の通信が増えるほど、identity、policy、routing、quota、traceを集約するgateway層の役割が大きくなる。</p>'},
      {heading:'技術トレンド',html:'<p>現実的な導入経路は、すべてのAgentを最初からA2A nativeにする方法だけではない。</p><ol><li>既存AgentにA2A CLIをtoolとして与える</li><li>remote Agentとの相互運用性と業務価値を確認する</li><li>常時利用する経路だけSDKによるnative実装へ移す</li></ol><p>これはREST APIをまず<code>curl</code>で試し、安定した利用箇所をclient libraryへ移す流れに近い。CLIは移行期のadapterと、障害時の診断ツールを兼ねられる。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>ホスティング運用であれば、既存のIncident AgentからA2A CLIを呼び、Diagnostic Agentへ調査を委譲する小さなPoCを組める。Diagnostic AgentはMCP経由でPrometheusやAlertmanagerを読み取る。</p><p>評価項目には回答精度だけでなく、Agent Cardの発見、認証情報の受け渡し、stream切断、timeout、exit code、JSON schema、trace IDの引き継ぎを含める。CLIを使うことで、運用チームが既に持つshell・scriptの知識を活用できる。</p><div class="insight"><span class="dialog-kicker">ADOPTION PATH</span><p>Phase 1: CLI bridge → Phase 2: A2A interoperability → Phase 3: 必要な経路だけnative A2A化。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>A2A CLIの認証、streaming、JSON出力の成熟</li><li>CLIをcoding harnessへ組み込む公式パターン</li><li>A2A SDK間の互換性とIntegration Testing Kit</li><li>A2AからMCP Toolへ至るend-to-end trace</li></ul>'}
    ],sources:[
      ['A2A CLI repository','https://github.com/a2aproject/a2a-cli'],
      ['A2A Go SDK','https://github.com/a2aproject/a2a-go'],
      ['A2A project','https://github.com/a2aproject/A2A']
    ]
  },
  {
    date:'2026-09-23', level:'MEDIUM', tags:['A2A','Operations'],
    title:'A2Aは仕様書から、検証可能な実装ecosystemへ',
    summary:'Specification、複数言語SDK、CLI、Inspector、TCK・ITKが揃うことで、Agent間通信をCIで確認できる段階へ進んでいる。',
    sections:[
      {heading:'今日のシグナル',html:'<p>A2Aの価値を判断する材料が、protocol specificationだけではなくなってきた。複数言語のSDK、CLI、Inspector、TCK、Integration Testing Kitが揃い、<strong>実装して接続し、互換性を試験する一連の道具</strong>が形成されている。</p>'},
      {heading:'重要ニュース',html:'<p>A2A projectではSpecificationと複数SDK、CLI、テスト関連リポジトリが活発に更新された。個々のcommitを正式な仕様変更とみなすことはできないが、protocolと実装・検証ツールが並行して整備されていることは確認できる。</p><p>Integration Testing Kitは、異なるSDK実装とversionをまたいだ互換性を確認することを目的としている。JSON-RPC、gRPC、HTTP+JSON/REST、streamingを含む経路を対象にしており、異種Agentの接続試験に使える。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>A2A — HIGH</strong><br>Specification → SDK → CLI / Inspector → TCK / ITKという開発・検証チェーンが見えてきた。A2Aを単なる通信仕様ではなく、実装ecosystemとして評価できる材料が増えている。</p><p><strong>MCP — MEDIUM</strong><br>A2AがAgent間の接続を扱い、MCPがAgentとToolの接続を扱う構成では、それぞれのconformanceを別に確認する必要がある。</p><p><strong>agentgateway / Agent Router — WATCH</strong><br>A2AとMCPの通信をgatewayへ集約する場合、protocolごとの認証・policy・traceをどう統一するかが次の論点になる。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>AAIFのHosted ProjectsやWorking Groupsについて、この日の観測では新規加入や卒業に相当する正式変更を確認していない。Technical Committeeやproject proposalsの正式な更新と、個別repositoryの活動は分けて記録する。</p>'},
      {heading:'技術トレンド',html:'<p>A2A ecosystemをKubernetesにたとえるなら、APIだけでなくclient libraries、操作用CLI、inspection、conformanceが揃う過程にある。成熟度は異なるが、productionで相互運用性を維持するには同じ種類の道具が必要になる。</p><p>Agent systemの品質は、LLMの回答だけでは決まらない。通信が仕様に適合し、異なるSDKでも同じtaskやeventを扱い、失敗時の状態が一貫していることが前提になる。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>Incident Agent → Diagnostic Agent → MCP Gateway → Infrastructureという構成なら、テストを次の3層へ分ける。</p><ul><li><strong>A2A protocol test</strong>：Agent Card、task、message、streaming、error model</li><li><strong>MCP protocol test</strong>：tool discovery、tool call、authorization、result</li><li><strong>業務E2E test</strong>：実際のアラートから正しい調査結果へ到達できるか</li></ul><p>この分割により、protocol不整合とAgentの推論ミスを混同しにくくなる。CIではTCK・ITKとconformanceを回し、定期的な業務シナリオでend-to-endを確認する構成が現実的だ。</p><div class="insight"><span class="dialog-kicker">OPERATOR NOTE</span><p>「回答が合っていた」だけでPoCを完了させず、異なるSDK、timeout、再接続、途中失敗も試験対象にする。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>A2Aの次期正式仕様とrelease notes</li><li>各SDKが同じ仕様へ追随するまでの時間差</li><li>TCKとITKのcoverage、CIへの組み込み例</li><li>MCP Conformanceとの組み合わせ</li><li>Identity & Trust、Observability & Traceabilityの設計</li></ul>'}
    ],sources:[
      ['A2A specification','https://github.com/a2aproject/A2A'],
      ['A2A Integration Testing Kit','https://github.com/a2aproject/a2a-itk'],
      ['A2A CLI','https://github.com/a2aproject/a2a-cli']
    ]
  },
  {
    date:'2026-09-22', level:'HIGH', tags:['MCP','Security','Operations'],
    title:'MCPは「接続する技術」から「壊さず運用する基盤」へ',
    summary:'Go SDKのresource exhaustion対策とprotocol version制御から、多数のMCP Serverを安全に運用するControl Planeを考える。',
    sections:[
      {heading:'今日のシグナル',html:'<p>MCP Go SDKの更新は、新機能の追加よりも<strong>大量接続されたMCPを壊さず、安全に運用するためのhardening</strong>が中心になった。MCPの開発重心がprotocol designだけでなくproduction engineeringへ移っている。</p>'},
      {heading:'重要ニュース',html:'<p>Go SDKではsession leak、deadlock、teardown時のhang、resource exhaustionに関する修正が進んだ。JSONのnesting、SSE event、stdio JSON-RPC frame、OAuth dynamic client registration responseに上限を設け、異常または巨大な入力がserver resourceを使い切るリスクを抑えている。</p><p><code>ServerOptions.SupportedProtocolVersions</code>により、serverがadvertise・negotiationするMCP versionを明示的に制限できる。最新版を一斉に有効化せず、stagingとproductionで対応versionを変える段階的なrolloutに利用できる。</p>'},
      {heading:'OSS別アップデート',html:'<p><strong>MCP — HIGH</strong><br>2026-07-28がSDKの最新対応revisionとして維持され、その運用安定化が進んでいる。Conformance suiteをclient/server双方へ適用する動きも、実装差異を検出するうえで重要になる。</p><p><strong>A2A — MEDIUM</strong><br>Specificationと複数SDK、Integration Testing Kitの更新が続いている。MCPと同様に、protocolだけでなく実装とconformanceへ投資する流れが見える。</p><p><strong>Agent Router / agentgateway — WATCH</strong><br>数十から数百のMCP Serverを扱う場合、個別接続ではなくgatewayやrouterでversion、identity、authorization、quota、observabilityを管理する必要が出てくる。</p>'},
      {heading:'ガバナンスと標準化',html:'<p>この日の確認範囲では、AAIFへの新しいHosted Project追加やfoundation全体の正式なガバナンス変更、重大なsecurity advisoryを確認していない。大型発表がない日でも、SDKのhardeningは実運用への成熟を示すため追跡対象になる。</p>'},
      {heading:'技術トレンド',html:'<p>Agentic infrastructureの通信経路は、Agent → MCP Server → Toolという単純な形から、次のようなControl Planeを含む形へ進む。</p><ul><li>Gateway / Routerによる接続先の管理</li><li>Protocol version negotiation</li><li>Identityとauthorization</li><li>入力上限、timeout、quota</li><li>Conformanceと互換性試験</li><li>OpenTelemetryによるtraceと監査</li></ul><p>MCPのversion lifecycleはKubernetes APIやTLS versionと同様に、対応版の明示、canary、廃止計画を必要とする。</p>'},
      {heading:'Agentic Opsへの示唆',html:'<p>Prometheus、Alertmanager、CMDB、SSH automationなどをMCP化すると、将来的には多数のMCP Serverが存在する。Agentが生成するJSONやSSEを信頼済みの内部通信とみなすと、誤動作がMCP ServerのOOMやControl Plane障害へ波及する可能性がある。</p><p>したがって、<strong>Agentが生成するtrafficもuntrusted inputとして制限・検証する</strong>。Productionでは安定版だけ、Stagingでは安定版と次期版を許可するなど、version制御をcanary rolloutに利用できる。</p><div class="insight"><span class="dialog-kicker">POC CHECKLIST</span><p>巨大JSON、深いnesting、長大なSSE、切断、session終了、timeout、旧versionとの接続を再現し、MCP Serverとgatewayのresource使用量を確認する。</p></div>'},
      {heading:'要ウォッチ項目',html:'<ul><li>MCP Go SDKのhardeningが他言語SDKへ波及するか</li><li>2026-07-28対応とconformanceの進捗</li><li>Server側のprotocol version制御事例</li><li>Agent RouterのMCP backendとauthorization</li><li>agentgatewayとの責務境界</li><li>Identity & Trust、Observability & Traceabilityの各WG</li></ul>'}
    ],sources:[
      ['MCP Go SDK releases','https://github.com/modelcontextprotocol/go-sdk/releases'],
      ['MCP specification 2026-07-28','https://modelcontextprotocol.io/specification/2026-07-28'],
      ['A2A project','https://github.com/a2aproject/A2A'],
      ['A2A Integration Testing Kit','https://github.com/a2aproject/a2a-itk']
    ]
  }
];
